### ISSUE TITLE
Fonts not loading?

### ISSUE THREAD

**Issue by ggloege** [CultivateMe/cm-marketing-site#1]
Most everything about this repo works fine on [Github pages](https://cultivateme.github.io/cm-marketing-site/) . But for some reason the font isn't loading and everything seems to be written in Times New Roman. I inspected several elements and, according to Chrome Dev Tools, they should be showing up as Source Sans Pro, inherited from `body` in `base.css`. But it sure doesn't look that way. Not sure how to debug this. @Rokotyan  can you help?

**Comment by Rokotyan** [comment]
@ggloege It works just fine for me. Did you try opening the site in another browser or on your phone?

**Comment by ggloege** [comment]
Everything is working now. Nikita identified the problem (HTTPS which is a new approach for github pages). Yay Nikita!
